name: E2E - Playwright tests

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # With no caching at all the entire ci process takes 4m 30s to complete!
  e2e-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run: docker compose -f local.yml build

      - name: Run DB Migrations
        run: docker compose -f local.yml run --rm django python manage.py migrate

      - name: Run localhost
        run: docker compose -f local.yml up -d

      - name: Install Python dependencies
        run: |
          cd e2e
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Wait for localhost
        run: |
          echo "Waiting for server to be ready..."
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            sleep 2
          done

      - name: Run E2E tests
        run: |
              cd e2e
              pytest tests/tests.py --reruns 3 --html=report.html --self-contained-html
        env:
         BASE_URL: ${{ secrets.BASE_URL }}
         USER_ADDRESS: ${{ secrets.USER_ADDRESS }}
         USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      
      - name: Upload failed test videos
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: failed-test-videos
          path: e2e/videos/*.webm

      - name: Tear down the Stack
        if: always()
        run: docker compose -f local.yml down

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: e2e-report
          path: e2e/report.html

